export enum ROUROU_TYPES {
  CASUAL_ROUROU = 'casual_rourou',
  LAUGHING_ROUROU = 'laughing_rourou',
  DOUBTFUL_ROUROU = 'doubtful_rourou',
  ADMIRING_ROUROU = 'admiring_rourou',
  ANGRY_ROUROU = 'angry_rourou',
  SURPRISED_ROUROU = 'surprised_rourou',
  SAD_ROUROU = 'sad_rourou',
}

export const ALL_ROUROU_TYPES = [
  ROUROU_TYPES.CASUAL_ROUROU,
  ROUROU_TYPES.LAUGHING_ROUROU,
  ROUROU_TYPES.DOUBTFUL_ROUROU,
  ROUROU_TYPES.ADMIRING_ROUROU,
  ROUROU_TYPES.ANGRY_ROUROU,
  ROUROU_TYPES.SURPRISED_ROUROU,
  ROUROU_TYPES.SAD_ROUROU,
]
